SolrNet/SolrNet

- SolrNet.Tests/DebugResponseParserTests.cs
- SolrNet.Tests/Resources/responseWithSimpleDebugDetails.xml
- SolrNet.Tests/Resources/responseWithStructuredDebugDetails.xml
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet/Commands/Parameters/CommonQueryOptions.cs
- SolrNet/Impl/DebugResults.cs
- SolrNet/Impl/ResponseParsers/DebugResponseParser.cs
- SolrNet/Impl/ResponseParsers/DefaultResponseParser.cs
- SolrNet/Impl/SolrQueryExecuter.cs
- SolrNet/SolrNet.csproj
- SolrNet/SolrQueryResults.cs
Debug details consist of:
1. Timing results(for process and prepare stage)
2. Explaination simple
3. Explaination structured
4. Parsed query
> Added "debug/explain" support

- Documentation/Querying.md
Added sample and explanation for ExtraParams and changed the url to point to the Apache Reference Guide
> Included ExtraParams and change URL to CWiki

- Documentation/Highlighting.md
Explains how to add additional parameters to highlighting via the use of ExtraParams
> Additional parameters for highlighting

- SolrNet.Tests/SolrDictionarySerializerTests.cs
- SolrNet.Tests/SolrDocumentSerializerTests.cs
- SolrNet.Tests/SolrDocumentSerializerTestsDocumentClasses.cs
- SolrNet/Impl/SolrDictionarySerializer.cs
- SolrNet/Impl/SolrDocumentSerializer.cs
> ISolrDocumentSerializer: handle multi-value field containing one or more nulls

- build.fsx
- lib/FAKE.exe.config
> Update ILMerge command

- AutofacContrib.SolrNet.Tests/AutofacContrib.SolrNet.Tests.csproj
- Castle.Facilities.SolrNetIntegration.Tests/Castle.Facilities.SolrNetIntegration.Tests.csproj
- NHibernate.SolrNet.Tests/NHibernate.SolrNet.Tests.csproj
- NHibernate.SolrNet.Tests/packages.config
- NHibernate.SolrNet/NHibernate.SolrNet.csproj
- NHibernate.SolrNet/packages.config
- Ninject.Integration.SolrNet.Tests/Ninject.Integration.SolrNet.Tests.csproj
- SolrNet.DSL.Tests/SolrNet.DSL.Tests.csproj
- SolrNet.DSL.Tests/packages.config
- SolrNet.DSL/SolrNet.DSL.csproj
- SolrNet.DSL/packages.config
- SolrNet.Tests.Integration/SolrNet.Tests.Integration.csproj
- SolrNet.Tests.Integration/packages.config
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet.Tests/packages.config
- SolrNet/SolrNet.csproj
- SolrNet/packages.config
- StructureMap.SolrNetIntegration.Tests/StructureMap.SolrNetIntegration.Tests.csproj
- Unity.SolrNetIntegration.Tests/App.config
- Unity.SolrNetIntegration.Tests/Unity.SolrNetIntegration.Tests.csproj
- Unity.SolrNetIntegration/Unity.SolrNetIntegration.csproj
- Unity.SolrNetIntegration/app.config
Upgrade all projects to use NuGet to fetch version 1.3 of Microsoft.Practices.ServiceLocation.
> Upgrade CommonServiceLocator to 1.3 through NuGet

- Unity.SolrNetIntegration.Tests/Unity.SolrNetIntegration.Tests.csproj
- Unity.SolrNetIntegration.Tests/packages.config
- Unity.SolrNetIntegration/Unity.SolrNetIntegration.csproj
- Unity.SolrNetIntegration/Unity.SolrNetIntegration.nuspec
- Unity.SolrNetIntegration/packages.config
> Update Unity to 4.0.1

- SolrNet/Impl/SolrConnection.cs
> Add Response Format as querystring paramater (wt=xml).

- SolrNet.Tests/SolrConstantScoreQueryTests.cs
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet/Impl/QuerySerializers/ConstantScoreQuerySerializer.cs
- SolrNet/Impl/QuerySerializers/DefaultQuerySerializer.cs
- SolrNet/SolrConstantScoreQuery.cs
> Add support for ConstantScore query

- SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsSolr4-.xml
- SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsSolr5+.xml
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet.Tests/SolrQueryResultsParserTests.cs
- SolrNet/Impl/CollationResult.cs
- SolrNet/Impl/ResponseParsers/SpellCheckResponseParser.cs
- SolrNet/Impl/SpellCheckResults.cs
Adding collations support.
Removing collation property as it is not part of the Solr response format.
> Adding collations support

- SolrNet.Cloud.Tests/SolrNet.Cloud.Tests.csproj
- SolrNet.Cloud.Tests/UnityTests.cs
- SolrNet.Cloud.Tests/app.config
- SolrNet.Cloud.Tests/packages.config
- SolrNet.Tests.Integration/App.config
- SolrNet.Tests.Integration/app.config
- SolrNet.sln
- Unity.SolrNetCloudIntegration/Collections/CollectionResolutionExtension.cs
- Unity.SolrNetCloudIntegration/Collections/CollectionResolutionStrategy.cs
- Unity.SolrNetCloudIntegration/Collections/CoupledToImplementationDetailsOverrideExtractor.cs
- Unity.SolrNetCloudIntegration/Collections/NullResolverOverrideExtractor.cs
- Unity.SolrNetCloudIntegration/Collections/ResolverOverrideExtractor.cs
- Unity.SolrNetCloudIntegration/SolrNetContainerConfiguration.cs
- Unity.SolrNetCloudIntegration/Unity.SolrNetCloudIntegration.csproj
- Unity.SolrNetCloudIntegration/packages.config
- Unity.SolrNetIntegration.Tests/App.config
- Unity.SolrNetIntegration.Tests/Unity.SolrNetIntegration.Tests.csproj
- Unity.SolrNetIntegration.Tests/UnityFixture.cs
- Unity.SolrNetIntegration.Tests/UnityIntegrationFixture.cs
- Unity.SolrNetIntegration.Tests/UnityMultiCoreFixture.cs
- Unity.SolrNetIntegration.Tests/packages.config
- Unity.SolrNetIntegration/Collections/CollectionResolutionExtension.cs
- Unity.SolrNetIntegration/Collections/CollectionResolutionStrategy.cs
- Unity.SolrNetIntegration/Collections/CoupledToImplementationDetailsOverrideExtractor.cs
- Unity.SolrNetIntegration/Collections/NullResolverOverrideExtractor.cs
- Unity.SolrNetIntegration/Collections/ResolverOverrideExtractor.cs
- Unity.SolrNetIntegration/SolrNetContainerConfiguration.cs
- Unity.SolrNetIntegration/Unity.SolrNetIntegration.csproj
- Unity.SolrNetIntegration/packages.config
Upgrade to unity 5.0
included EnterpriseLibrary Common for the Guard class
> upgrade Unity 5.0.0

- Castle.Facilities.SolrNetIntegration.Tests/CastleFixture.cs
- Castle.Facilities.SolrNetIntegration/SolrCore.cs
- Castle.Facilities.SolrNetIntegration/SolrNetFacility.cs
- SolrNet/Impl/SolrPostConnection.cs
> Support for PostSolrConnections in SolrNet.Windsor

- SolrNet.Tests/AttributesMappingManagerTests.cs
- SolrNet/Mapping/AttributesMappingManager.cs
- changelog.md
> Better error message when type has duplicate SolrField

- SolrNet.Cloud.Tests/SolrCloudStateProviderTests.cs
- SolrNet.Cloud.Tests/SolrNet.Cloud.Tests.csproj
- SolrNet.Cloud.Tests/UnityTests.cs
- SolrNet.Cloud/Exceptions/SolrNetCloudConnectionException.cs
- SolrNet.Cloud/ZooKeeperClient/SolrCloudStateProvider.cs
Seems to be the core issue with #385
> SolrNet Cloud: add checks if connection is valid

- SolrNet.Tests/Resources/responseWithSpellCheckingExtended.xml
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet.Tests/SolrQueryResultsParserTests.cs
- SolrNet/Impl/ResponseParsers/SpellCheckResponseParser.cs
Handling scenario when spellcheck.extendedResults=true
> Fix for 397

- SolrNet/Commands/AtomicUpdateCommand.cs
- changelog.md
Content stream was closed prematurely.
Fixes #395
> Fix async AtomicUpdate issue

- SolrNet.Tests/MappingManagerTests.cs
- SolrNet/Mapping/MappingManager.cs
You can now specify to force the usage of the reflected type when adding a property mapping.
> Fixes #406

- SolrNet.Tests/SolrFacetFieldQueryTests.cs
- SolrNet/Impl/FacetQuerySerializers/SolrFacetFieldQuerySerializer.cs
- SolrNet/SolrFacetFieldQuery.cs
Added Contain, ContainsIgnoreCase and Exists properties to olrFacetFiledQuery object. All required tests were also implemented.
> Missing properties for SolrFacetFieldQuery

- Documentation/Initialization.md
- Microsoft.DependencyInjection.SolrNet.Tests/Microsoft.DependencyInjection.SolrNet.Tests.csproj
- README.md
- SimpleInjector.SolrNet.Tests/SimpleInjector.SolrNet.Tests.csproj
- SimpleInjector.SolrNet.Tests/SimpleInjectorFixture.cs
- SimpleInjector.SolrNet.Tests/SimpleInjectorIntegrationFixture.cs
- SimpleInjector.SolrNet/ContainerExtensions.cs
- SimpleInjector.SolrNet/SimpleInjector.SolrNet.csproj
- SimpleInjector.SolrNet/SolrCore.cs
- SimpleInjector.SolrNet/SolrNetOptions.cs
- SolrNet.sln
- added module to support Simple Injector
> added SimpleInjector support

- Microsoft.DependencyInjection.SolrNet/ServiceCollectionExtensions.cs
- SimpleInjector.SolrNet/ContainerExtensions.cs
> Fix AttributeMapping to use MemoizingMappingManager

- SolrNet.Cloud.Tests/SolrNet.Cloud.Tests.csproj
- SolrNet.Cloud.Tests/packages.config
- SolrNet.Cloud/SolrNet.Cloud.csproj
- SolrNet.Cloud/SolrNet.Cloud.nuspec
- Unity.SolrNetCloudIntegration/Unity.SolrNetCloudIntegration.csproj
> Updated ZooKeeperNetEx version to 3.4.12.1

- Documentation/Core-admin.md
This seems to be in line with the current version of the API.
> Update Unload Command of Core-admin.md

- Castle.Facilities.SolrNetIntegration.Tests/CastleFixture.cs
- Castle.Facilities.SolrNetIntegration.Tests/CastleIntegrationFixture.cs
- Castle.Facilities.SolrNetIntegration/SolrNetFacility.cs
[#472](https://github.com/SolrNet/SolrNet/issues/472) fixed (I hope!)
> Updated Obsolete Codes in Castle Windsor Configurations

- SolrNet.Cloud/SolrCloudStateParser.cs
- SolrNet.Cloud/ZooKeeperClient/SolrCloudStateProvider.cs
Fixes #425 
Please review if I missed something here.
> SolrCloudStateProvider changes

- Documentation/Multi-core-instance.md
> Added Autofac multicore example

- SolrNet.Tests.Common/Mocks/HttpWebRequest.cs
- SolrNet/HttpWebAdapters/IHttpWebRequest.cs
- SolrNet/HttpWebAdapters/Impl/HttpWebRequestAdapter.cs
- SolrNet/Impl/SolrPostConnection.cs
Resolves https://github.com/SolrNet/SolrNet/issues/501
> Update SolrPostConnection to use IHttpWebRequestFactory

- AutofacContrib.SolrNetCloud/AutofacContrib.SolrNetCloud.csproj
- AutofacContrib.SolrNetCloud/SolrNetCloudModule.cs
- SolrNet.sln
> Autofac Integration for SolrNet.Cloud

- SolrNet/Impl/ResponseParsers/ExtractResponseParser.cs
There is a typo in the parsing of the XML response.
> Fixes bug #173

- SolrNet.Tests.Integration/AutoSolrConnectionTests.cs
- SolrNet.Tests/SolrNet.Tests.csproj
- SolrNet.Tests/UriValidatorTests.cs
- SolrNet/Impl/AutoSolrConnection.cs
- SolrNet/Utils/UriValidator.cs
- solr/Dockerfile
Fixes https://github.com/SolrNet/SolrNet/pull/516/
> Fix for AutoSolrConnection and very long requests

- SolrNet/Group.cs
- SolrNet/Impl/AbstractSolrQueryResults.cs
- SolrNet/Impl/ResponseParsers/GroupingResponseParser.cs
- SolrNet/Impl/ResponseParsers/ResultsResponseParser.cs
To prevent OverflowException
Should fix #555
> Use long not int to represent total number of results

- SolrNet.Tests/AtomicUpdateCommandTests.cs
- SolrNet.Tests/SolrOperationsTests.cs
- SolrNet/Commands/AtomicUpdateCommand.cs
Update case for `commitWithin` parameter in `AtomicUpdateCommand`
> Update case for commitWithin parameter in AtomicUpdateCommand

- Documentation/Atomic-updates.md
- README.md
> Add doc for atomic update
