SolrNet.Tests/Resources/responseWithStats.xml
SolrNet.Tests/SolrQueryResultsParserTests.cs
SolrNet/Impl/ResponseParsers/StatsResponseParser.cs

I have experienced errors parsing these statnodes coming from solr 5.2
`<null name="min" /> <null name="max" /> <double name="mean">NaN</double>`
`<double name="mean">NaN</double>`
is parsed to double.NaN
Empty like `<null name="min" />`
can not parse and is set to double.NaN

Enable parsing of statnodes like <null name="min" /> <double name="mean">NaN</double>

---

StructureMap.SolrNetIntegration.Tests/StructureMap.SolrNetIntegration.Tests.csproj
StructureMap.SolrNetIntegration.Tests/StructureMapFixture.cs
StructureMap.SolrNetIntegration.Tests/StructureMapIntegrationFixture.cs
StructureMap.SolrNetIntegration.Tests/StructureMapMultiCoreFixture.cs
StructureMap.SolrNetIntegration.Tests/packages.config
StructureMap.SolrNetIntegration/SolrNetRegistry.cs
StructureMap.SolrNetIntegration/StructureMap.SolrNetIntegration.csproj
StructureMap.SolrNetIntegration/StructureMap.SolrNetIntegration.nuspec
StructureMap.SolrNetIntegration/packages.config

Update unit tests, and integration tests. 
The integration tests that fail, also used to fail, so that's ok.
As never have used StructureMap, I used PR #186, that deals with updating to StructureMap 3, to make the changes. So knowing the changes are the same, and the unit tests pass, I'm confident about this PR.

Update StructureMap to 4.5.2, with help of PR #186

---

Castle.Facilities.SolrNetIntegration/Castle.Facilities.SolrNetIntegration.nuspec

The NuSpec file created an empty NuGet package.
Merging this to master as this should be a hotfix, and should be released asap.
Fixes #331

Hotfix: Fix nuspec file for Windsor

---

SolrNet.Cloud.Tests/FakeOperations.cs
SolrNet.Cloud/SolrCloudBasicOperations.cs
SolrNet.Cloud/SolrCloudOperations.cs
SolrNet.Tests.Common/Mocks/MSolrBasicOperations.cs
SolrNet.Tests.Common/Mocks/MSolrOperations.cs
SolrNet.Tests.Integration/IntegrationFixture.cs
SolrNet.Tests.Integration/SolrNet.Tests.Integration.csproj
SolrNet.Tests/AtomicUpdateCommandTests.cs
SolrNet.Tests/SolrOperationsTests.cs
SolrNet/AtomicUpdateSpec.cs
SolrNet/Commands/AtomicUpdateCommand.cs
SolrNet/ISolrBasicOperations.cs
SolrNet/ISolrOperations.cs
SolrNet/Impl/SolrBasicServer.cs
SolrNet/Impl/SolrServer.cs

Xavier/gjunge,
I have completed my work on the atomic updates feature (original details here https://github.com/SolrNet/SolrNet/pull/339).
A couple of points to note:
1. The web requests are implemented using json. This is different to how the other commands have been implemented (xml). The reason for this is that the solr documentation for atomic updates is very limited and no examples exist using xml. Unfortunately, I didn't have time to reverse engineer the mechanism. As solr supports both, I don't think this should be an issue, but it felt necessary to explain the inconsistency.
2. The integration test will not work with the version of solr which forms part of the solrNet distribution. This version is very old and does not support the full set of atomic update modifiers. I have ran …

Issue 108: Added support for atomic updates

---

SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsNoExtendedSolr4-.xml
SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsNoExtendedSolr5+.xml
SolrNet.Tests/SolrNet.Tests.csproj
SolrNet.Tests/SolrQueryResultsParserTests.cs
SolrNet/Impl/CollationResult.cs
SolrNet/Impl/ResponseParsers/SpellCheckResponseParser.cs

Adding support when spellcheck.collateExtendedResults is set to false (true by default).
This commit fixes the issue described in https://github.com/SolrNet/SolrNet/issues/310.

Extending collations support

---

Castle.Facilities.SolrNetIntegration.Tests/CastleFixture.cs
Castle.Facilities.SolrNetIntegration/SolrCore.cs
Castle.Facilities.SolrNetIntegration/SolrNetFacility.cs
SolrNet/Impl/SolrPostConnection.cs

Allowing Multicore support for Post Connections
Also changed Post Connection to pass in XML as the parameter so SolrNet can parse correctly (was getting errors because later Solr versions return JSON by default instead of XML.

Support for PostSolrConnections in SolrNet.Windsor

---

SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsDuplicatesSolr4-.xml
SolrNet.Tests/Resources/responseWithSpellCheckingAndCollationsDuplicatesSolr5+.xml
SolrNet.Tests/SolrNet.Tests.csproj
SolrNet.Tests/SolrQueryResultsParserTests.cs
SolrNet/Impl/CollationResult.cs
SolrNet/Impl/ResponseParsers/SpellCheckResponseParser.cs

Fixed issue when collation result contains duplicates in misspellings and corrections.
Example:
```xml
<lst name="collations">
<lst name="collation">
<str name="collationQuery">audit differences audit</str>
<long name="hits">1111</long>
<lst name="misspellingsAndCorrections">
<str name="aodit">audit</str>
<str name="differencex">differences</str>
<str name="aodit">audit</str>
</lst>
</lst>   
</lst>
```

Collations issue fix

---

AutofacContrib.SolrNet/AutofacContrib.SolrNet.csproj
Castle.Facilities.SolrNetIntegration/Castle.Facilities.SolrNetIntegration.csproj
CommonServiceLocator.SolrNet.Cloud/CommonServiceLocator.SolrNet.Cloud.csproj
CommonServiceLocator.SolrNet/CommonServiceLocator.SolrNet.csproj
Microsoft.DependencyInjection.SolrNet/Microsoft.DependencyInjection.SolrNet.csproj
NHibernate.SolrNet/NHibernate.SolrNet.csproj
Ninject.Integration.SolrNet/Ninject.Integration.SolrNet.csproj
SolrNet.Cloud/SolrNet.Cloud.csproj
SolrNet.DSL/SolrNet.DSL.csproj
SolrNet.Tests/AutoSolrConnectionTests.cs
SolrNet/ISolrConnection.cs
SolrNet/Impl/AutoSolrConnection.cs
SolrNet/Impl/SolrQueryExecuter.cs
SolrNet/SolrNet.csproj
StructureMap.SolrNetIntegration/StructureMap.SolrNetIntegration.csproj
Unity.SolrNetCloudIntegration/Unity.SolrNetCloudIntegration.csproj
Unity.SolrNetIntegration/Unity.SolrNetIntegration.csproj
changelog.md

* `HttpClient` instead of `HttpWebRequest` to perform requests to Solr, making cleaner code, and out-of-the-box instrumentation by 3rd party libraries such NewRelic.
* Auto `POST`s when the `GET` uri is too long.
* Falls back to `PostSolrConnection` for sync methods
* New `GetAsync`/`PostAsync` method with `CancellationToken` support, and return of` Stream` instead of `string` for improved performance. (We can feed a stream into the `XDocument`, instead of first creation a string, and then parsing that string into the `XDocument`).

Added AutoSolrConnection

---

Documentation/Initialization.md
StructureMap.SolrNetIntegration.Tests/StructureMapFixture.cs
StructureMap.SolrNetIntegration.Tests/StructureMapIntegrationFixture.cs
StructureMap.SolrNetIntegration.Tests/StructureMapMultiCoreFixture.cs
StructureMap.SolrNetIntegration/SolrNetRegistry.cs

Changed implementation for ISolrConnection from SolrConnection to AutoSolrConnection
Changed the class to be more extensible
Updated test fixtures
Warning: Interface has changed. 
SolrNetRegistry must be created with SolrNetRegistry.Create static method instead of constructor. 
This had to be done in order to safely use virtual methods at initialization time.

Use AutoSolrConnection instead of SolrConnection in StructureMap.SolrNetIntegration

---

Microsoft.DependencyInjection.SolrNet.Tests/MicrosoftDependencyFixture.cs
Microsoft.DependencyInjection.SolrNet/ServiceCollectionExtensions.cs
Microsoft.DependencyInjection.SolrNet/SolrNetOptions.cs

* Switch to Singleton AutoSolrConnection
* Add override to IServiceCollection.AddSolrNet , allowing to set injection options. Currently only supporting tweaking the HttpClient in use by the AutoSolrConnection.
* Add unit test showing the use of Basic Authentication.
Fixes #402

MS Dependency Injection update

---

Documentation/Overriding-mapper.md

- It's just necessary to change the default container, not replace it. Before that, I was receiving exceptions about failures on dependency injection.

Fixing issue #423

---

SolrNet/Impl/QuerySerializers/QueryInListSerializer.cs
SolrNet/SolrQueryInList.cs

QueryInListSerializer was automatically quoting all values which made it impossible to use queries in form: Year: *. Added Quoted property similarly to the one SolrQueryField is using to allow for skipping quoting. It's true by default.

QueryInListSerializer should not always auto quote 

---

Microsoft.DependencyInjection.SolrNet.Tests/MicrosoftDependencyFixture.cs
Microsoft.DependencyInjection.SolrNet/ServiceCollectionExtensions.cs

Now for dot net core adding typed instance doesn't set its authentication header which is fixed with this commit.

Set Http client basic authentication header for typed instance.

---

SolrNet.Tests/AtomicUpdateCommandTests.cs
SolrNet/Commands/AtomicUpdateCommand.cs
SolrNet/SolrNet.csproj

Issue #445 highlights a bug in the json serialization for AtomicUpdateCommand where special characters like `"` and `\n` are incorrectly serialized before being sent to solr. This changes `GetAtomicUpdateJson()` to use the Newtonsoft.Json package to handle the serialization. 
Additionally, the serialization change in this PR fixes another issue with `AtomicUpdateCommand`, preventing SolrNet from passing in null values of type `string` and `string[]` to solr. This is used for explicitly deleting a field in atomic updates.
> Set or replace the field value(s) with the specified value(s), or remove the values if 'null' or empty list is specified as the new value.
[Solr Documentation](https://lucene.apache.org/solr/guide/6_6/updating-parts-of-documents.html#UpdatingPartsofDocuments-AtomicUpdate …

Fix json serialization issues in AtomicUpdateCommand

---

SimpleInjector.SolrNet.Tests/SimpleInjectorLifestyleTests.cs
SimpleInjector.SolrNet/ContainerExtensions.cs

When container default lifestyle scoped (for example web application) - lifetime mismatch.

SimpleInjector registration improvement fix issue 460

---

SolrNet.Tests/AtomicUpdateCommandTests.cs
SolrNet/Commands/AtomicUpdateCommand.cs

Atomic Update Increment Command Name is produced as "ınc" in Turkish locale. It should be independent of current locale. The correct command should be "inc". 
The issue is described in #474

Atomic Update Command Name Bugfix

---

SolrNet/Impl/AutoSolrConnection.cs

This happens when the contentType param is null. Solr is ok with this param not existing so it can choose the right extractor for you.
SolrConnection has this null check as well.

Fix for AutoSolrConnection throwing an ArgumentNullException 

---

Microsoft.DependencyInjection.SolrNet/ServiceCollectionExtensions.cs

and thereby reuse HttpClient instances
fix  #551

Reuse Solr connection

---

SolrNet/Impl/AutoSolrConnection.cs
SolrNet/Impl/SolrConnection.cs
SolrNet/Impl/SolrPostConnection.cs

Added constructors to various connection types so we can gain control over the usage of IHttpWebRequestFactory.
Asynchronous requests use HttpClient which is injected via constructors already.
For synchronous requests the connection types now hardcode the use of HttpWebRequestFactory, and thus don't support a custom implementation (or BasicAuthHttpWebRequestFactory in my use-case).

Add constructors to gain control over httpwebrequestfactories for synchronous operations

---

.gitignore
AutofacContrib.SolrNet.Tests/AutofacIntegrationFixture.cs
Castle.Facilities.SolrNetIntegration.Tests/CastleIntegrationFixture.cs
LightInject.SolrNet.Tests/LightInject.SolrNet.Tests.csproj
LightInject.SolrNet.Tests/packages.lock.json
LightInject.SolrNet/LightInject.SolrNet.csproj
LightInject.SolrNet/packages.lock.json
Ninject.Integration.SolrNet.Tests/NinjectIntegrationFixture.cs
SimpleInjector.SolrNet.Tests/SimpleInjectorIntegrationFixture.cs
SolrNet.Cloud.Tests/packages.lock.json
SolrNet.Tests.Integration/IntegrationFixtureTestAuthentication.cs
SolrNet.Tests.Integration/SolrNet.Tests.Integration.csproj
SolrNet.Tests.Integration/packages.lock.json
StructureMap.SolrNetIntegration.Tests/StructureMapIntegrationFixture.cs
Unity.SolrNetIntegration.Tests/UnityIntegrationFixture.cs
integration_tests.sh

Updated integration_tests.sh;
- Enabled execution of all integration tests
- Disabled execution of cloud integration tests
- Added another docker instance that has basic auth enabled
- Added multiple collections/cores, just to the default docker instance, required by various integration tests
Solution;
- Fixed failing integration tests
- Added integration tests to SolrNet.Tests to verify if basic auth is working, for both sync and async requests
- Lowered LightInject package version

Fix integration tests
